Traceback (most recent call last):
  File "C:\Users\miaha\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\miaha\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load libraries
import pandas as pd
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
import os
from os import path
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import STOPWORDS
from collections import OrderedDict, defaultdict, Counter
import pandas as pd
import csv
from nltk.tokenize import TweetTokenizer
from sklearn.feature_extraction.text import CountVectorizer
import tokenize
from nltk.tokenize import word_tokenize
from tokenize import tokenize
import itertools
from PIL import Image
from wordcloud import WordCloud
#from ggplot import *

# Read the data
ep4_file = r"C:\\Users\\kahma\\Downloads\\star-wars-movie-scripts\\star-wars-movie-scripts\\SW_EpisodeIV.txt"
ep5_file = r"C:\\Users\\kahma\\Downloads\\star-wars-movie-scripts\\star-wars-movie-scripts\\SW_EpisodeV.txt"
ep6_file = r"C:\\Users\\kahma\\Downloads\\star-wars-movie-scripts\\star-wars-movie-scripts\\SW_EpisodeVI.txt"
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_10260/404331327.py[0m in [0;36m<module>[1;34m[0m
[0;32m     13[0m [1;32mimport[0m [0mcsv[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m [1;32mfrom[0m [0mnltk[0m[1;33m.[0m[0mtokenize[0m [1;32mimport[0m [0mTweetTokenizer[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 15[1;33m [1;32mfrom[0m [0msklearn[0m[1;33m.[0m[0mfeature_extraction[0m[1;33m.[0m[0mtext[0m [1;32mimport[0m [0mCountVectorizer[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     16[0m [1;32mimport[0m [0mtokenize[0m[1;33m[0m[1;33m[0m[0m
[0;32m     17[0m [1;32mfrom[0m [0mnltk[0m[1;33m.[0m[0mtokenize[0m [1;32mimport[0m [0mword_tokenize[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'sklearn'
ModuleNotFoundError: No module named 'sklearn'

